### ISSUE TITLE
Change !events to show all upcoming events by default

### ISSUE THREAD

**Issue by kpaasial** [NovaFox161/DisCal-Discord-Bot#16] opened 2018-02-09 12:57 UTC
I think it would be a good idea that !events would by default show all upcoming events. If I were just a user 
who wants to look up and sign up for events I would expect that !events shows all of the upcoming events.

If the number of events shown is too much there could be a configurable setting in the bot that limits the amount of shown events to a certain number.

**Comment by zanassu** [comment] 2018-02-10 14:02
You can in fact use !events <number>, with up to 15 events being displayed. The full information is not supplied like when just typing !events, but is condensed to help list better. You should be able to find the right event and get a detailed view from there, or list the events of the day like you mentioned :)

**Comment by kpaasial** [comment] 2018-02-10 14:24
But my point is that using plain "!events" shows only the first upcoming event. To see more events I have to use "!events number", i.e. "!events 5". I want "!events" to give at least a concise list of all upcoming events.

**Comment by NovaFox161** [comment] 2018-02-13 14:37
This is done by design. It's impossible to list all upcoming events because users could have thousands of events and by listing all upcoming events we would max out the Google Calendar and Discord APIs.

We can bump the long list to a high max than 15, but we won't be changing the `!events` without a number to having multiple events displayed as that was the original design and quickly caused issues among many servers.

**Comment by NovaFox161** [comment] 2019-03-19 18:14
Gonna close this since its been like a year plus the design has changed from the original.

**Closed by NovaFox161** 2019-03-19 18:14 UTC
